general {
  lock_cmd = desktop-power lock
  before_sleep_cmd = desktop-power lock-only
  after_sleep_cmd = sleep 1 && desktop-power wake
  on_unlock_cmd = desktop-power wake
  inhibit_sleep = 3
}

listener {
  timeout = 600
  on-timeout = display-brightness idle-dim; keyboard-brightness off
  on-resume = display-brightness idle-restore; keyboard-brightness restore
}

listener {
  timeout = 900
  on-timeout = desktop-power lock-only
}

listener {
  timeout = 930
  on-timeout = hyprctl dispatch dpms off
  on-resume = desktop-power wake
}

listener {
  timeout = 2100
  on-timeout = desktop-power idle-suspend
}
