general {
  lock_cmd = desktop-power lock
  before_sleep_cmd = desktop-power lock-only
  after_sleep_cmd = sleep 1 && desktop-power wake
  inhibit_sleep = 3
}

listener {
  timeout = 300
  on-timeout = desktop-power lock
  on-resume = desktop-power wake
}

listener {
  timeout = 330
  on-timeout = hyprctl dispatch dpms off
  on-resume = desktop-power wake
}

