# Laptop multimedia keys for volume and LCD brightness (with OSD)
bindeld = ,XF86AudioRaiseVolume, Volume up, exec, desktop-osd --output-volume raise
bindeld = ,XF86AudioLowerVolume, Volume down, exec, desktop-osd --output-volume lower
bindeld = ,XF86AudioMute, Mute, exec, desktop-osd --output-volume mute-toggle
bindeld = ,XF86AudioMicMute, Mute microphone, exec, audio-input-mute
bindeld = ,XF86MonBrightnessUp, Brightness up, exec, display-brightness +5%
bindeld = ,XF86MonBrightnessDown, Brightness down, exec, display-brightness 5%-
bindeld = SHIFT, XF86MonBrightnessUp, Brightness maximum, exec, display-brightness 100%
bindeld = SHIFT, XF86MonBrightnessDown, Brightness minimum, exec, display-brightness 1%
bindeld = ,XF86KbdBrightnessUp, Keyboard brightness up, exec, keyboard-brightness up
bindeld = ,XF86KbdBrightnessDown, Keyboard brightness down, exec, keyboard-brightness down
bindld = ,XF86KbdLightOnOff, Keyboard backlight cycle, exec, keyboard-brightness cycle
bindld = ,XF86TouchpadToggle, Toggle touchpad, exec, touchpad-toggle
bindld = ,XF86TouchpadOn, Enable touchpad, exec, touchpad-toggle on
bindld = ,XF86TouchpadOff, Disable touchpad, exec, touchpad-toggle off

# Precise 1% multimedia adjustments with Alt modifier
bindeld = ALT, XF86AudioRaiseVolume, Volume up precise, exec, desktop-osd --output-volume +1
bindeld = ALT, XF86AudioLowerVolume, Volume down precise, exec, desktop-osd --output-volume -1
bindeld = ALT, XF86MonBrightnessUp, Brightness up precise, exec, display-brightness +1%
bindeld = ALT, XF86MonBrightnessDown, Brightness down precise, exec, display-brightness 1%-

# Requires playerctl
bindld = , XF86AudioNext, Next track, exec, desktop-osd --playerctl next
bindld = , XF86AudioPause, Pause, exec, desktop-osd --playerctl play-pause
bindld = , XF86AudioPlay, Play, exec, desktop-osd --playerctl play-pause
bindld = , XF86AudioPrev, Previous track, exec, desktop-osd --playerctl previous

# Switch audio output with Super + Mute
bindld = SUPER, XF86AudioMute, Switch audio output, exec, audio-output-switch
