#!/bin/bash

set -Eeuo pipefail
source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)/scripts/lib/common.sh"

backup_root="$HOME/.local/state/arch-setup/backups/$(date +%Y%m%d-%H%M%S)"
mkdir -p "$backup_root"

if pgrep -x mako >/dev/null 2>&1; then
  note "Stopping Mako before switching notification daemons"
  pkill -x mako
  for _ in {1..20}; do
    pgrep -x mako >/dev/null 2>&1 || break
    sleep 0.1
  done
fi

remove_legacy_mako_link() {
  local path=$1 raw_target link_target
  [[ -L $path ]] || return 0
  raw_target=$(readlink -- "$path")
  if [[ $raw_target == /* ]]; then
    link_target=$(realpath -m -- "$raw_target")
  else
    link_target=$(realpath -m -- "$(dirname -- "$path")/$raw_target")
  fi
  [[ $link_target == "$SETUP_ROOT/dotfiles/mako" || $link_target == "$SETUP_ROOT/dotfiles/mako/"* ]] || return 0
  rm -f -- "$path"
  note "Removed legacy Mako link $path"
}

remove_legacy_mako_link "$HOME/.config/mako/config"
remove_legacy_mako_link "$HOME/.config/mako"
rmdir "$HOME/.config/mako" 2>/dev/null || true

remove_legacy_helper_link() {
  local helper=$1 path target
  path="$HOME/.local/bin/$helper"
  [[ -L $path ]] || return 0
  target=$(realpath -m -- "$(dirname -- "$path")/$(readlink -- "$path")")
  [[ $target == "$SETUP_ROOT/dotfiles/bin/.local/bin/$helper" ]] || return 0
  rm -f -- "$path"
  note "Removed legacy helper link $path"
}

remove_legacy_helper_link webapp-launch
remove_legacy_helper_link gmail-handler

backup_conflicts() {
  local package=$1 source_file relative target backup
  while IFS= read -r -d '' source_file; do
    relative=${source_file#"$SETUP_ROOT/dotfiles/$package/"}
    target="$HOME/$relative"
    local parent="$HOME" component
    IFS=/ read -ra components <<<"$(dirname "$relative")"
    for component in "${components[@]}"; do
      [[ -n $component && $component != "." ]] || continue
      parent="$parent/$component"
      if [[ -L $parent ]]; then
        backup="$backup_root/${parent#"$HOME/"}"
        mkdir -p "$(dirname "$backup")"
        mv "$parent" "$backup"
        mkdir -p "$parent"
        note "Backed up linked directory $parent"
      fi
    done
    [[ -e $target || -L $target ]] || continue
    [[ -L $target && $(readlink -f "$target") == $(readlink -f "$source_file") ]] && continue
    backup="$backup_root/$relative"
    mkdir -p "$(dirname "$backup")"
    mv "$target" "$backup"
    note "Backed up $target"
  done < <(find "$SETUP_ROOT/dotfiles/$package" -type f -print0)
}

note "Backing up dotfile conflicts"
for package_dir in "$SETUP_ROOT"/dotfiles/*; do
  package=$(basename "$package_dir")
  backup_conflicts "$package"
done

obsolete_hypr_files=(
  environment.conf looknfeel.conf input.conf windows.conf media.conf clipboard.conf
  tiling.conf bindings.conf autostart.conf hyprland.conf apps.conf
  apps/bitwarden.conf apps/browser.conf apps/hyprshot.conf apps/jetbrains.conf
  apps/localsend.conf apps/pip.conf apps/steam.conf apps/system.conf
  apps/telegram.conf apps/terminals.conf apps/walker.conf apps/webcam-overlay.conf
)
for file in "${obsolete_hypr_files[@]}"; do
  path="$HOME/.config/hypr/$file"
  if [[ -L $path ]]; then
    rm -f "$path"
  fi
done

# Hyprland auto-generates a hyprlang hyprland.conf stub if it can't find
# hyprland.lua at the moment it starts. Once our real hyprland.lua is in
# place, this stub is stale and Hyprland ends up loading it instead.
hyprland_stub="$HOME/.config/hypr/hyprland.conf"
if [[ -f $hyprland_stub && ! -L $hyprland_stub ]] && grep -q '^autogenerated = 1$' "$hyprland_stub" 2>/dev/null; then
  note "Removing Hyprland's auto-generated stub hyprland.conf"
  rm -f "$hyprland_stub"
fi

note "Linking dotfiles with Stow"
for package_dir in "$SETUP_ROOT"/dotfiles/*; do
  stow --no-folding --restow --dir="$SETUP_ROOT/dotfiles" --target="$HOME" "$(basename "$package_dir")"
done

if pgrep -x swaync >/dev/null 2>&1; then
  note "Reloading SwayNC configuration"
  swaync-client --reload-config || true
  swaync-client --reload-css || true
elif [[ -n ${WAYLAND_DISPLAY:-} ]]; then
  note "Starting SwayNC for the current Wayland session"
  setsid uwsm-app -- swaync >/dev/null 2>&1 &
  disown
fi

if pgrep -x hypridle >/dev/null 2>&1; then
  note "Restarting Hypridle to apply idle policy changes"
  pkill -x hypridle
  for _ in {1..20}; do
    pgrep -x hypridle >/dev/null 2>&1 || break
    sleep 0.1
  done
  setsid uwsm-app -- hypridle >/dev/null 2>&1 &
  disown
elif [[ -n ${WAYLAND_DISPLAY:-} ]]; then
  note "Starting Hypridle for the current Wayland session"
  setsid uwsm-app -- hypridle >/dev/null 2>&1 &
  disown
fi

local_dir="$HOME/.config/hypr/local"
mkdir -p "$local_dir"
for file in monitors.lua input.lua environment.lua autostart.lua; do
  [[ -e $local_dir/$file ]] || touch "$local_dir/$file"
done

weather_dir="$HOME/.config/weather-status"
mkdir -p "$weather_dir"
[[ -e $weather_dir/location ]] || touch "$weather_dir/location"

wallpaper_dir="$HOME/.config/wallpapers"
mkdir -p "$wallpaper_dir"
rsync -a "$SETUP_ROOT/assets/wallpapers/" "$wallpaper_dir/"
ARCH_SETUP_WALLPAPER_DIR="$wallpaper_dir" \
  "$SETUP_ROOT/dotfiles/bin/.local/bin/wallpaper-start" --set-only
if [[ -n ${WAYLAND_DISPLAY:-} ]]; then
  note "Switching the current Wayland session to awww"
  ARCH_SETUP_WALLPAPER_DIR="$wallpaper_dir" \
    "$SETUP_ROOT/dotfiles/bin/.local/bin/wallpaper-start" --apply
fi

if [[ -z $(find "$backup_root" -type f -o -type l | head -1) ]]; then
  rmdir -p "$backup_root" 2>/dev/null || true
fi

if pgrep -x waybar >/dev/null 2>&1; then
  note "Restarting waybar to apply config changes"
  pkill -x waybar
  setsid uwsm-app -- waybar >/dev/null 2>&1 &
  disown
fi
