# Define terminal tag to style them uniformly
windowrule = tag +terminal, match:class Alacritty
windowrule = tag -default-opacity, match:tag terminal
windowrule = opacity 0.985 0.96, match:tag terminal
